services:

  frontend:
    user: "1000:1000"
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      args:
        MODE: ${FRONTEND_MODE}
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app_modules

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      args:
        MODE: ${FRONTEND_MODE}
    ports:
      - "80:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html:ro
      - /srv/media/new:/media/new:ro
      - /home/darkflade/Pictures/Wallpapers:/media/old:ro
    depends_on:
      - backend
      - frontend

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: glab
      POSTGRES_USER: glab
      POSTGRES_PASSWORD: seeckreet
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  redis:
    image: redis:alpine
    ports:
      - "127.0.0.1:6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data

  backend:
    build: ./backend
    env_file: .env
    volumes:
      - /srv/media/new:/media/new
    depends_on:
      - postgres
      - redis

  file_validator_worker:
    build:
      context: .
      dockerfile: ./workers/Dockerfile.validator
    env_file: .env
    volumes:
      - /srv/media/new:/media/new
    depends_on:
      - postgres
      - redis

  thumbnailer_worker:
    build:
      context: .
      dockerfile: ./workers/Dockerfile.thumbnailer
    env_file: .env
    command: ["./thumbnailer_worker"]
    volumes:
      - /srv/media/new:/media/new
    depends_on:
      - postgres
      - redis

volumes:
  pgdata:
  redisdata:
  frontend_node_modules:
